All:
	@echo "----------Building project:[ Test - Debug ]----------"
	@cd "C:\Users\dmitry.tsvetkov\Documents\GitHub\StartPP\Test" && "$(MAKE)" -f  "Test.mk"
clean:
	@echo "----------Cleaning project:[ Test - Debug ]----------"
	@cd "C:\Users\dmitry.tsvetkov\Documents\GitHub\StartPP\Test" && "$(MAKE)" -f  "Test.mk" clean
.PHONY: clean All

