.PHONY: clean All

All:
	@echo "----------Building project:[ StartPP - Debug OSX ]----------"
	@"$(MAKE)" -f  "StartPP.mk"
clean:
	@echo "----------Cleaning project:[ StartPP - Debug OSX ]----------"
	@"$(MAKE)" -f  "StartPP.mk" clean
