.PHONY: clean All

All:
	@echo "----------Building project:[ StartPP - Debug ]----------"
	@"$(MAKE)" -f  "StartPP.mk"
clean:
	@echo "----------Cleaning project:[ StartPP - Debug ]----------"
	@"$(MAKE)" -f  "StartPP.mk" clean
