//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StartPP.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_TOOLBAR_VIEW                101
#define IDS_TOOLBAR_PROJ                102
#define IDP_FAILED_OPEN_DATABASE        103
#define IDS_TOOLBAR_FILTER              104
#define IDS_TOOLBAR_OPERATIONS          105
#define IDS_TOOLBAR_TOOLS               106
#define IDS_SELECT_BASE_NODE            107
#define IDS_PIPES_COPIED                108
#define IDS_PARTS_NOT_CONNECTED         109
#define IDS_SELECT_MODE_HELPSTRING      110
#define IDS_NODE_BEG                    111
#define IDS_NODE_BEG_C                  112
#define IDS_NODE_END                    113
#define IDS_NODE_END_C                  114
#define IDS_PIPE_TYPE                   115
#define IDS_PODZEM                      116
#define IDS_NADZEM                      117
#define IDS_GEOM                        118
#define IDR_POPUP_EDIT                  119
#define IDS_PROJ_X                      119
#define IDS_PROJ_X_C                    120
#define IDS_PROJ_Y                      121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDS_PROJ_Y_C                    126
#define IDS_PROJ_Y2                     127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_PROJ_Y_C2                   129
#define IDR_MFCApplication1TYPE         130
#define IDR_StartPPTYPE                 130
#define ID_WINDOW_MANAGER               131
#define IDS_PROJ_Z                      132
#define IDS_PROJ_Z_C                    133
#define IDS_LEN_PLAN                    134
#define IDS_LEN_PLAN_C                  135
#define IDS_LEN_GEN                     136
#define IDS_LEN_GEN_C                   137
#define ID_DUMMY_COMPILE                138
#define IDS_APLAN_ABS                   138
#define ID_DEL_NODE                     139
#define IDS_APLAN_ABS_C                 140
#define IDS_APLAN_REL                   141
#define IDS_APLAN_REL_C                 142
#define IDS_APROF                       143
#define IDS_APROF_C                     144
#define ID_SORTING_GROUPBYTYPE          145
#define IDS_UKLON                       145
#define ID_SORTING_SORTALPHABETIC       146
#define IDS_UKLON_C                     146
#define ID_SORTING_SORTBYTYPE           147
#define IDS_DIAM                        147
#define ID_SORTING_SORTBYACCESS         148
#define IDS_DIAM_C                      148
#define IDS_MATERIAL                    149
#define IDS_MATERIAL_C                  150
#define ID_PROP_SV                      151
#define ID_PROP_OTV_IZ                  152
#define ID_PROP_ARM                     153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PIPE_TABLE_WND              157
#define IDS_PROPERTIES_WND              158
#define IDS_NOTO                        159
#define IDS_NOTO_C                      160
#define IDI_FILE_VIEW                   161
#define IDS_RATO                        161
#define IDI_FILE_VIEW_HC                162
#define IDS_RATO_C                      162
#define IDI_CLASS_VIEW                  163
#define IDS_RADA                        163
#define IDI_CLASS_VIEW_HC               164
#define IDS_RADA_C                      164
#define IDI_OUTPUT_WND                  165
#define IDS_DABI                        165
#define IDI_OUTPUT_WND_HC               166
#define IDS_DABI_C                      166
#define IDI_PROPERTIES_WND              167
#define IDS_RATE                        167
#define IDI_PROPERTIES_WND_HC           168
#define IDS_RATE_C                      168
#define IDS_POG_VESA                    169
#define IDB_EXPLORER_24                 170
#define IDS_VETR                        170
#define IDR_SORT                        171
#define IDS_VETR_C                      171
#define IDB_SORT_24                     172
#define IDS_VEIZ                        172
#define IDS_VEIZ_C                      173
#define IDS_VEPR                        174
#define IDB_FILE_VIEW                   175
#define IDS_VEPR_C                      175
#define IDB_FILE_VIEW_24                176
#define IDS_ADDITIONAL                  176
#define IDB_CLASS_VIEW                  177
#define IDS_KOPE                        177
#define IDB_CLASS_VIEW_24               178
#define IDS_KOPE_C                      178
#define IDR_MENU_IMAGES                 179
#define IDS_KOPR                        179
#define IDB_MENU_IMAGES_24              180
#define IDS_KOPR_C                      180
#define ID_TOOLS_MACRO                  181
#define IDS_ADD_NAGR                    181
#define IDS_NAGV                        182
#define IDR_PROPERTIES                  183
#define IDS_NAGV_C                      183
#define IDS_NAGX                        184
#define IDS_NAGX_C                      185
#define IDS_NAGY                        186
#define IDS_NAGY_C                      187
#define IDS_NAGZ                        188
#define IDS_NAGZ_C                      189
#define IDS_GRUNT                       190
#define IDS_DIAM_KOZHUX                 191
#define IDS_DIAM_KOZHUX_C               192
#define IDS_GLUB                        193
#define IDS_BEG_GLUB                    194
#define IDS_BEG_GLUB_C                  195
#define IDS_END_GLUB                    196
#define IDS_END_GLUB_C                  197
#define IDS_VIZA                        198
#define IDS_SHTR                        199
#define IDR_THEME_MENU                  200
#define IDS_SHTR_C                      200
#define IDS_GRUNT_TYPE                  201
#define IDS_GRUNT_UP                    202
#define IDS_GRUNT_UP_C                  203
#define IDS_GRUNT_OSN                   204
#define ID_VIEW_APPLOOK_WIN_2000        205
#define IDS_GRUNT_OSN_C                 205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define IDS_GRUNT_SIDE                  206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define IDS_GRUNT_SIDE_C                207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define IDS_NODE                        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define IDS_NODE_C                      209
#define ID_VIEW_APPLOOK_VS_2008         210
#define IDS_NONE                        210
#define IDS_ARMAT                       211
#define IDS_OTVIZ                       212
#define IDS_OTVSV                       213
#define IDS_OTVFL                       214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define IDS_KO                          215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define IDS_KU                          216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define IDS_TR                          217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_VREZKA                      218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_IZD                         219
#define IDS_IZD_C                       220
#define IDS_AR_LEN                      221
#define IDS_AR_LEN_C                    222
#define IDS_AR_VES                      223
#define IDS_AR_VES_C                    224
#define IDS_OTV_RAD                     225
#define IDS_OTV_RAD_C                   226
#define IDS_OTV_VES                     227
#define IDS_OTV_VES_C                   228
#define IDS_OTV_MAT                     229
#define IDS_OTV_MAT_C                   230
#define IDS_OTV_NOTO                    231
#define IDS_OTV_NOTO_C                  232
#define IDS_OTV_RATO                    233
#define IDS_OTV_RATO_C                  234
#define IDS_KO_SEFF                     235
#define IDS_KO_SEFF_C                   236
#define IDS_KO_OS_HOD                   237
#define IDS_KO_OS_HOD_C                 238
#define IDS_KO_PODATL                   239
#define IDS_KO_PODATL_C                 240
#define IDS_KU_PODATL                   241
#define IDS_KU_PODATL_C                 242
#define IDS_KU_LEN                      243
#define IDS_KU_LEN_C                    244
#define IDS_TR_MAT                      245
#define IDS_TR_MAT_C                    246
#define IDS_TR_VES                      247
#define IDS_TR_VES_C                    248
#define IDS_MAGISTRAL                   249
#define IDS_MAG_NOTO                    250
#define IDS_MAG_NOTO_C                  251
#define IDS_MAG_RATO                    252
#define IDS_MAG_RATO_C                  253
#define IDS_MAG_LEN                     254
#define IDS_MAG_LEN_C                   255
#define IDS_OTV                         256
#define IDS_OTV_DIAM                    257
#define IDS_OTV_DIAM_C                  258
#define IDS_OSN                         259
#define IDS_FORMAT_PIPE                 260
#define IDS_FORMAT_NODE                 261
#define IDS_FORMAT_MANY_PIPES           262
#define IDS_FORMAT_NODE2                263
#define IDS_FORMAT_PIPE2                264
#define IDS_PODJOM                      265
#define IDS_OPUSK                       266
#define IDS_FORMAT_UCH_UZL              267
#define IDS_FORMAT_PIPE_EXISTS          268
#define IDS_ARMAT_TABLE                 269
#define IDS_STRING270                   270
#define IDS_AT_DIAM                     271
#define IDS_AT_S                        272
#define IDS_AT_C1                       273
#define IDS_AT_ROTV                     274
#define IDS_AT_VESOTV                   275
#define IDS_AT_LZADV                    276
#define IDS_AT_VESZADV                  277
#define IDS_AT_NAGRMERT                 278
#define IDS_AT_NAGRSK                   279
#define IDS_F_DIAM                      281
#define IDS_F_NAMA                      282
#define IDS_F_NTOS                      283
#define IDS_STRING284                   284
#define IDS_F_VETR                      285
#define IDS_F_VEIZ                      286
#define IDS_F_VEPR                      287
#define IDS_F_RADA                      288
#define IDS_F_DABI                      289
#define IDS_F_DIAM_KOZH                 290
#define IDS_F_VIZA                      291
#define IDS_F_VIZA2                     292
#define IDS_F_SHTR                      293
#define IDS_F_PELI                      294
#define IDS_F_PEUG                      295
#define IDS_F_LEN                       296
#define IDS_F_APROF                     297
#define IDS_DEL_PIPES_Q                 298
#define IDS_MN_NO_PIPES_UZ              299
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_MN_2PIPES_IN                303
#define IDS_MN_NO_PIPES_OUT             304
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDS_MN_2_PIPES_OUT              307
#define IDS_MN_NULL_LEN                 308
#define IDS_MN_IZLOM                    309
#define IDD_PIPEDESCDIALOG              310
#define IDS_MN_TOO_MUCH_LEN             310
#define IDR_VIEW_TOOLBAR                311
#define IDS_NODE_EXISTS                 311
#define IDD_ARMATTABLEDLG               312
#define IDS_MORE_ONE_BLANK_LINE         312
#define ID_VIEW_CUSTOMIZE               313
#define IDC_PAN                         313
#define IDS_PIPES_MUSTBE_MORE1          313
#define IDC_ROTATE                      314
#define ID_VIEW_PROPERTIESWND           314
#define IDS_DIST_SUM_MORE_PIPE_LEN      314
#define ID_VIEW_PIPE_TABLE_WND          315
#define IDC_SELECT                      315
#define IDS_PDD_AIR                     315
#define IDC_ZOOM                        316
#define IDS_PDD_WATER                   316
#define IDC_ZOOM_IN_OUT                 317
#define IDS_PDD_NO_PERFORM              317
#define IDR_FILTER                      318
#define IDS_PDD_RD_10_400_01_PDN        318
#define IDS_PDD_RD_10_400_01_PDK        319
#define IDR_OPERATIONS                  320
#define IDS_PDD_BY_WATER                320
#define IDS_PDD_BY_AIR                  321
#define IDD_NEW_PIPE                    322
#define IDS_PDD_PERFORM                 322
#define IDD_DEL_PIPES                   323
#define IDS_NORMA_OST                   323
#define IDD_MULT_PIPES                  324
#define IDS_NORMA_MVN                   324
#define IDD_COPY_PARAMS                 325
#define IDS_NORMA_MN                    325
#define IDD_NEW_NODE                    326
#define IDS_NORMA_OST24                 326
#define IDD_MOVE_NODE                   327
#define IDS_NORMA_LISEGA                327
#define IDR_TOOLS                       328
#define IDS_WORK                        328
#define IDS_COLD                        329
#define IDD_DIST                        330
#define IDS_STRING330                   330
#define IDD_PIPES_DIALOG                331
#define IDS_PT_MAT                      331
#define IDS_PT_QTR                      332
#define IDR_POPUP_TABLE                 333
#define IDS_PT_QI                       333
#define IDR_MENU_PROJ                   334
#define IDS_PT_QP                       334
#define IDR_TOOLBAR_PROJ                335
#define IDS_PT_DIZ                      335
#define IDS_PT_ROTV                     336
#define IDD_SPUSK_DIALOG                337
#define IDS_PT_VESARM                   337
#define IDB_BITMAP_SPUSK                338
#define IDD_ADD_SCHEM                   338
#define IDS_PT_MATOTV                   338
#define IDB_VREZ45                      339
#define IDS_PT_SOTV                     339
#define IDB_GUS                         340
#define IDS_PT_C1OTV                    340
#define IDB_PARALEL                     341
#define IDS_PT_SEFF                     341
#define IDS_PT_KPOD                     342
#define IDS_OTVL_NOTO                   343
#define IDS_OTVL_NOTO_C                 344
#define IDS_OTVL_RATO                   345
#define IDS_OTVL_RATO_C                 346
#define IDS_OTVL_VYS                    347
#define IDS_OTVL_VYS_C                  348
#define IDS_NAKL                        349
#define IDS_NAKL_NOTO                   350
#define IDS_NAKL_NOTO_C                 351
#define IDS_NAKL_SHIR                   352
#define IDS_NAKL_SHIR_C                 353
#define IDS_VR_KOPR                     354
#define IDS_VR_KOPR_C                   355
#define IDS_VR_NAKL                     356
#define IDS_VR_NAKL_NOTO                357
#define IDS_VR_NAKL_NOTO_C              358
#define IDS_VR_NAKL_SHIR                359
#define IDS_VR_NAKL_SHIR_C              360
#define IDS_MERT                        361
#define IDS_SK                          362
#define IDS_NAPR                        363
#define IDS_UPR                         364
#define IDS_ZHESTK_PODV                 365
#define IDS_OPOR                        366
#define IDS_OPOR_C                      367
#define IDS_MERT_O                      368
#define IDS_SK_O                        369
#define IDS_NAPR_O                      370
#define IDS_SK_KOTR                     371
#define IDS_SK_KOTR_C                   372
#define IDS_UPR_O                       373
#define IDS_UPR_NTG                     374
#define IDS_UPR_NTG_C                   375
#define IDS_UPR_IZM_NAGR                376
#define IDS_UPR_IZM_NAGR_C              377
#define IDS_UPR_KZAP                    378
#define IDS_UPR_KZAP_C                  379
#define IDS_UPR_PODD_US                 380
#define IDS_UPR_PODD_US_C               381
#define IDS_UPR_PODATL                  382
#define IDS_ZHP_LEN_TYAGI               383
#define IDS_ZHP_LEN_TYAGI_C             384
#define IDS_RAST                        385
#define IDS_SG                          386
#define IDS_DEF                         387
#define IDS_DEF_C                       388
#define IDS_DEF_RAST                    389
#define IDS_DEF_SG                      390
#define IDS_DEF_RSTSG_C                 391
#define IDS_NAGR                        392
#define IDS_NAGR_VES_ADD                393
#define IDS_UZ_SILVES                   394
#define IDS_UZ_SILVES_C                 395
#define IDS_UZ_MOMVESX                  396
#define IDS_UZ_MOMVESX_C                397
#define IDS_UZ_MOMVESY                  398
#define IDS_UZ_MOMVESY_C2               399
#define IDS_NAGR_NONVES_ADD             400
#define IDS_UZ_SILX                     401
#define IDS_UZ_SILX_C                   402
#define IDS_UZ_SILY                     403
#define IDS_UZ_SILY_C2                  404
#define IDS_UZ_SILZ                     405
#define IDS_UZ_SILZ_C                   406
#define IDS_UZ_MOMX                     407
#define IDS_UZ_MOMX_C                   408
#define IDS_UZ_MOMY                     409
#define IDS_UZ_MOMY_C                   410
#define IDS_UZ_MOMZ                     411
#define IDS_UZ_MOMZ_C                   412
#define IDS_UPR_PODATL_C                413
#define IDS_PT_SHTR                     414
#define IDB_BITMAP1                     414
#define IDS_PT_PIPE_TYPE                415
#define IDB_BITMAP2                     415
#define IDS_PT_SIZ                      416
#define IDB_BITMAP3                     416
#define IDS_PT_PODZ                     417
#define IDB_BITMAP4                     417
#define IDS_PT_NADZ                     418
#define IDB_BITMAP5                     418
#define IDS_PT_DEL_LINE_Q               419
#define IDB_BITMAP6                     419
#define IDS_DELETE_NODE_Q               420
#define IDS_MN_IZLOM1                   421
#define IDS_RENUM_NODES_Q               422
#define IDS_UNITE_NODES_Q               423
#define IDS_F_RTOS                      424
#define IDS_TR_TABLE                    425
#define IDS_C                           426
#define IDS_DIAM_SHT                    427
#define IDS_S_SHT                       428
#define IDS_C_SHT                       429
#define IDS_VYS_SHT                     430
#define IDS_SHIR_NAKL                   431
#define IDS_TOLSCH_NAKL                 432
#define IDS_VES_TR                      433
#define IDS_KORPUS                      434
#define IDC_COMBO1                      1000
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_LIST1                       1002
#define IDC_EDIT3                       1003
#define IDC_PIPES                       1003
#define IDC_PARAMS                      1004
#define IDC_EDIT_DIST_X                 1004
#define IDC_PIPE_NAME                   1005
#define IDC_EDIT_DIST_Y                 1005
#define IDC_CHECK1                      1006
#define IDC_EDIT_DIST_Z                 1006
#define IDC_RADIO1                      1007
#define IDC_RADIO2                      1008
#define IDC_STATIC1                     1008
#define IDC_EDIT_FROM                   1009
#define IDC_RADIO3                      1009
#define IDC_EDIT_TO                     1010
#define IDC_RADIO4                      1010
#define IDC_EDIT_DIST_ALL               1011
#define IDC_EDIT_T_SET                  1013
#define IDC_EDIT_TIME_WORK              1014
#define IDC_COMBO_ISP                   1015
#define IDC_EDIT_T_TEST                 1016
#define IDC_COMBO_STRINGS               1017
#define IDC_COMBO_COMP                  1018
#define IDC_COMBO_STRINGS2              1019
#define IDC_EDIT_DESC                   1020
#define IDC_COMBO_NORMA_DOC             1021
#define IDC_DATETIMEPICKER1             1022
#define IDC_STATIC_T_ISP                1023
#define IDC_STATIC13                    1024
#define IDC_COMBO_STRINGS3              1025
#define IDC_STATIC_T_Z                  1026
#define IDC_EDIT_T_Z                    1027
#define IDC_STATIC14                    1028
#define IDC_STATIC15                    1029
#define IDC_STATIC18                    1030
#define IDC_STATIC19                    1031
#define IDC_STATIC17                    1032
#define IDC_GRID                        1035
#define IDC_LIST_DIAM                   1035
#define IDC_IMAGE                       1036
#define IDC_ABOUT_VER                   1037
#define ID_ZOOM_IN                      32771
#define ID_ZOOM_OUT                     32772
#define ID_ZOOM_ALL                     32773
#define ID_ZOOM_WIN                     32774
#define ID_PAN                          32775
#define ID_ROTATE                       32776
#define ID_SELECT                       32777
#define ID_VIEW_NODE_NUMS               32783
#define ID_VIEW_SIZES                   32785
#define ID_VIEW_APROF                   32786
#define ID_VIEW_ELEMENTS                32787
#define ID_VIEW_NODES                   32788
#define ID_NEW_PIPE                     32791
#define ID_DEL_PIPE                     32792
#define ID_COPY_PIPE_PARAMS             32793
#define ID_NEW_NODE                     32794
#define ID_INVERT_PIPE                  32795
#define ID_MOVE_NODE                    32797
#define ID_RENUM_PIPES                  32799
#define ID_MULT_PIPE                    32808
#define ID_SHOW_OGL                     32817
#define ID_UNDO                         32818
#define ID_REDO                         32819
#define ID_IMPORT_DBF                   32822
#define ID_DIST                         32823
#define ID_PIPE_DESC                    32825
#define ID_EXPORT_INI                   32828
#define ID_PIPE_TABLE                   32830
#define ID_ARMAT_TABLE                  32832
#define ID_TABLE_DEL                    32834
#define ID_TROINICS_TABLE               32836
#define ID_VIEW_3DVIEWS_TOP             32839
#define ID_VIEW_3DVIEWS_BOTTOM          32840
#define ID_VIEW_3DVIEWS_LEFT            32841
#define ID_VIEW_3DVIEWS_RIGHT           32842
#define ID_VIEW_3DVIEWS_FRONT           32843
#define ID_VIEW_3DVIEWS_BACK            32844
#define ID_VIEW_3DVIEWS_SW_ISO          32845
#define ID_VIEW_3DVIEWS_SE_ISO          32846
#define ID_VIEW_3DVIEWS_NE_ISO          32847
#define ID_VIEW_3DVIEWS_NW_ISO          32848
#define ID_VIEW_3DVIEWS_DIMETRY         32849
#define ID_Spusk                        32864
#define ID_ADD_SCHEM                    32866
#define ID_PROP_SK                      32876
#define ID_PROP_MERT                    32877
#define ID_PROP_NAPR                    32878
#define ID_PROP_OTV_SV                  32879
#define ID_IND_FILE_INFO                32880
#define ID_IND_FILE_COUNT               32881
#define ID_Menu                         32893

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        420
#define _APS_NEXT_COMMAND_VALUE         32895
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           315
#endif
#endif
