#ifndef STRINGS_H
#define STRINGS_H

#define IDS_NODE_BEG_C          "Узел начала участка"
#define IDS_NODE_END            "Узел конца"
#define IDS_NODE_END_C          "Узел конца участка"
#define IDS_PIPE_TYPE           "Тип участка"
#define IDS_PODZEM              "Подземный"
#define IDS_NADZEM              "Надземный"
#define IDS_GEOM                "Геометрия"
#define IDS_PROJ_X              "ПроекцияX, м"
#define IDS_PROJ_X_C            "Проекция участка на ось X"
#define IDS_PROJ_Y              "ПроекцияY, м"
#define IDS_STATUS_PANE1        "Панель 1"
#define IDS_STATUS_PANE2        "Панель 2"
#define IDS_TOOLBAR_STANDARD    "Стандартная"
#define IDS_TOOLBAR_CUSTOMIZE   "Настройка..."
#define IDS_PROJ_Y_C            "Проекция участка на ось Y"
#define IDS_PROJ_Y2             "ПроекцияY, м"
#define IDS_APROF_C             "Угол в профиле (азимутальный)"
#define IDS_UKLON               "Уклон, 1/1000"
#define IDS_UKLON_C             "Уклон трубопровода (1000 = 45 град)"
#define IDS_DIAM                "Диаметр трубы, мм"
#define IDS_DIAM_C              "Диаметр трубы"
#define IDS_MATERIAL            "Материал трубы"
#define IDS_MATERIAL_C          "Материал трубы"
#define ID_PROP_SV              "Вставка сварного отвода\nСварной отвод"
#define ID_PROP_OTV_IZ          "Вставка изогнутого отвода в узле\nОтвод изогнутый"
#define ID_PROP_ARM             "Вставка арматуры в узле\nАрматура"
#define ID_EXPAND_ALL           "Распахнуть все ветки свойств\nРаспахнуть все"
#define IDS_FILE_VIEW           "Представление файлов"
#define IDS_CLASS_VIEW          "Представление классов"
#define IDS_PIPE_TABLE_WND      "Таблица труб"
#define IDS_PROPERTIES_WND      "Свойства"
#define IDS_NOTO                "Толщина стенки трубы, мм"
#define IDS_MN_NO_PIPES_OUT     "Из узла %d не выходит ни один участок!"
#define IDS_EXPLORER            "Проводник"
#define IDS_EDIT_MENU           "Редактировать"
#define IDS_MN_2_PIPES_OUT      "Из узла %d выходит 2 или более участков!"
#define IDS_MN_NULL_LEN         "Нулевая длина одного из участков"
#define IDS_MN_IZLOM            "Точка излома в узле %g"
#define IDS_MN_TOO_MUCH_LEN     "Расстояние превышает длину участка!"
#define IDS_NODE_EXISTS         "Узел %d уже существует"
#define IDS_MORE_ONE_BLANK_LINE "Более одной пустой строки"
#define IDS_PIPES_MUSTBE_MORE1  "Число участков должно быть больше 1"
#define IDS_DIST_SUM_MORE_PIPE_LEN "Сумма расстояний превышает длину участка"
#define IDS_PDD_AIR             "воздуx (газ)"
#define IDS_PDD_WATER           "вода"
#define IDS_PDD_NO_PERFORM      "не проводить"
#define IDS_PDD_RD_10_400_01_PDN "РД 10-400-01 (режим ПДН) Тепловые сети"
#define IDS_PDD_RD_10_400_01_PDK "РД 10-400-01 (режим ПДК) Тепловые сети"
#define IDS_F_RADA              "Рабочее давление"
#define IDS_F_DABI              "Давление испытания"
#define IDS_F_DIAM_KOZH         "Диаметр кожуха изоляции"
#define IDS_F_VIZA              "Высота засыпки грунта (начало)"
#define IDS_F_VIZA2             "Высота засыпки грунта (конец)"
#define IDS_F_SHTR              "Ширина траншеи"
#define IDS_F_PELI              "Определять лин. перемещения"
#define IDS_F_PEUG              "Определять угл. перемещения"
#define IDS_F_LEN               "Длина участка"
#define IDS_F_APROF             "Угол в профиле"
#define IDS_DEL_PIPES_Q         "Удалить %d участков?"
#define IDS_MN_NO_PIPES_UZ      "В узел %d нет входящих участков!"
#define IDS_BUILD_TAB           "Сборка"
#define IDS_DEBUG_TAB           "Отладка"
#define IDS_FIND_TAB            "Найти"
#define IDS_MN_2PIPES_IN        "В узел %d входит 2 или более участков!"
#define ID_ZOOM_IN              "Увеличение масштаба\nУвеличить"
#define ID_ZOOM_OUT             "Уменьшение масштаба\nУменьшить"
#define ID_ZOOM_ALL             "Показать весь документ\nПоказать все"
#define ID_ZOOM_WIN             "Масштабирование рамкой\nМасшт. рамкой"
#define ID_PAN                  "Панорамирование\nПанорамирование"
#define ID_ROTATE               "Вращение схемы\nВращение"
#define ID_SELECT               "Выбор участка\nВыбор"
#define ID_VIEW_NODE_NUMS       "Показать номера узлов\nНомера узлов"
#define ID_VIEW_SIZES           "Показать размеры\nРазмеры"
#define ID_VIEW_APROF           "Показать углы в профиле\nУглы в профиле"
#define ID_VIEW_ELEMENTS        "Показать элементы в узлах\nЭлементы"
#define ID_VIEW_NODES           "Показать отметки узлов\nУзлы"
#define ID_NEW_PIPE             "Создать новый участок\nНовый участок"
#define ID_DEL_PIPE             "Удалить участки\nУдалить участки"
#define ID_COPY_PIPE_PARAMS     "Копирование параметров участка\nКопирование параметров"
#define ID_NEW_NODE             "Ввести новые узлы на участке\nРазбить участок"
#define ID_INVERT_PIPE          "Поменять местами начальный и конечный узел участка\nИнвертировать узлы"
#define ID_MOVE_NODE            "Передвинуть узел на прямом участке\nПередвинуть узел"
#define ID_RENUM_PIPES          "Перенумеровать узлы на схеме\nПеренумеровать"
#define ID_MULT_PIPE            "Размножить участок\nРазмножить участок"
#define ID_VIEW_3DVIEWS_TOP     "Показать модель сверху\nПлан"
#define ID_VIEW_3DVIEWS_BOTTOM  "Показать модель снизу\nСнизу"
#define ID_VIEW_3DVIEWS_LEFT    "Показать модель слева\nСлева"
#define ID_VIEW_3DVIEWS_RIGHT   "Показать модель справа\nСправа"
#define ID_VIEW_3DVIEWS_FRONT   "Показать модель спереди\nСпереди"
#define ID_VIEW_3DVIEWS_BACK    "Показать модель сзади\nСзади"
#define ID_VIEW_3DVIEWS_SW_ISO  "Показать модель в юго-западной изометрии\nЮЗ изометрия"
#define ID_VIEW_3DVIEWS_SE_ISO  "Показать модель в юго-восточной изометрии\nЮВ изометрия"
#define ID_VIEW_3DVIEWS_NE_ISO  "Показать модель в северо-восточной изометрии\nСВ изометрия"
#define ID_VIEW_3DVIEWS_NW_ISO  "Показать модель в северо-западной изометрии\nСЗ изометрия"
#define ID_Spusk                "Вставка спускников  и ответвлений\nСпуск. и отв."
#define ID_ADD_SCHEM            "Вставка другой схемы в текущую"
#define ID_PROP_SK              "Вставка скользящей опоры в узле\nСкользящая опора"
#define ID_PROP_MERT            "Вставка мертвой опоры в узле\nМёртвая опора"
#define ID_PROP_NAPR            "Вставка направляющей опоры в узле\nНаправляющая опора"
#define ID_PROP_OTV_SV          "Вставка сварного отвода в узле\nОтвод сварной"
#define ID_SHOW_OGL             "Показ модели в 3D виде\n3D вид"
#define ID_UNDO                 "Отмена последнего действия\nОтменить"
#define ID_REDO                 "Повторное выполнение последнего действия\nВернуть"
#define ID_IMPORT_DBF           "Импорт схемы трубопровода из файла *.DBF"
#define ID_PIPE_DESC            "Отобразить окно параметров расчета\nПараметры расчета"
#define ID_EXPORT_INI           "Экспорт текущей схемы в файл открытого формата Старт *.ini"
#define IDS_NOTO_C              "Номинальная толщина стенки трубы"
#define IDS_RATO                "Технологическое утонение, мм"
#define IDS_RATO_C              "Технологическое утонение"
#define IDS_RADA                "Расчетное давление, кгс/кв.см"
#define IDS_RADA_C              "Расчетное давление"
#define IDS_DABI                "Давление испытания, кгс/кв.см"
#define IDS_DABI_C              "Давление испытания"
#define IDS_RATE                "Расчетная температура, °C"
#define IDS_RATE_C              "Расчетная температура"
#define IDS_POG_VESA            "Погонные веса, кгс/м"
#define IDS_VETR                "Трубы, кгс/м"
#define IDS_VETR_C              "Погонный вес трубы"
#define IDS_VEIZ                "Изоляции, кгс/м"
#define IDS_VEIZ_C              "Погонный вес изоляции"
#define IDS_VEPR                "Продукта, кгс/м"
#define IDS_VEPR_C              "Погонный вес продукта"
#define IDS_ADDITIONAL          "Дополнительные"
#define IDS_KOPE                "Коэф. прочн. на давл. сварн. соединения"
#define IDS_KOPE_C              "Коэффициент прочности сварного соединения на давление"
#define IDS_KOPR                "Коэф. прочн. на изгиб сварн. соединения"
#define IDS_KOPR_C              "Коэффициент прочности сварного соединения на изгиб"
#define IDS_ADD_NAGR            "Дополнительные нагрузки, кгс/м"
#define IDS_NAGV                "Сила от веса, кгс/м"
#define IDS_NAGV_C              "Сила от веса"
#define IDS_NAGX                "X невесовая сила, кгс/м"
#define IDS_NAGX_C              "Невесовая сила по оси X"
#define IDS_NAGY                "Y невесовая сила, кгс/м"
#define IDS_NAGY_C              "Невесовая сила по оси Y"
#define IDS_NAGZ                "Z невесовая сила, кгс/м"
#define IDS_NAGZ_C              "Невесовая сила по оси Z"
#define IDS_GRUNT               "Грунт"
#define IDS_DIAM_KOZHUX         "Диаметр кожуха, мм"
#define IDS_DIAM_KOZHUX_C       "Диаметр кожуха изоляции"
#define IDS_GLUB                "Глубина заложения, м"
#define IDS_BEG_GLUB            "в начале участка, м"
#define IDS_BEG_GLUB_C          "В начале участка"
#define IDS_END_GLUB            "в конце участка, м"
#define IDS_END_GLUB_C          "В конце участка"
#define IDS_VIZA                "Высота засыпки, м"
#define IDS_SHTR                "Ширина траншеи, м"
#define IDS_SHTR_C              "Ширина траншеи"
#define IDS_GRUNT_TYPE          "Тип грунта"
#define IDS_GRUNT_UP            "Сверху"
#define IDS_GRUNT_UP_C          "Тип грунта засыпки (сверху)"
#define IDS_GRUNT_OSN           "Oснования"
#define IDS_GRUNT_OSN_C         "Тип грунта основания"
#define IDS_GRUNT_SIDE          "Cбоку"
#define IDS_GRUNT_SIDE_C        "Тип грунта сбоку"
#define IDS_NODE                "Узел"
#define IDS_NODE_C              "Узел конца участка"
#define IDS_NONE                "Нет"
#define IDS_ARMAT               "Арматура"
#define IDS_OTVIZ               "Oтвод изогнутый"
#define IDS_OTVSV               "Oтвод сварной"
#define IDS_OTVFL               "Oтвод фланцевый"
#define IDS_KO                  "Kомпенсатор осевой"
#define IDS_KU                  "Kомпенсатор угловой"
#define IDS_TR                  "Тройник сварной"
#define IDS_VREZKA              "Сварная врезка"
#define IDS_IZD                 "Изделие"
#define IDS_IZD_C               "Тип изделия в узле"
#define IDS_AR_LEN              "Длина, м"
#define IDS_AR_LEN_C            "Длина арматуры"
#define IDS_AR_VES              "Вес, кг"
#define IDS_AR_VES_C            "Вес арматуры"
#define IDS_OTV_RAD             "Радиус, м"
#define IDS_OTV_RAD_C           "Радиус отвода"
#define IDS_OTV_VES             "Вес, кг"
#define IDS_OTV_VES_C           "Вес отвода"
#define IDS_OTV_MAT             "Материал"
#define IDS_OTV_MAT_C           "Материал отвода"
#define IDS_OTV_NOTO            "Номинальная толщина стенки, мм"
#define IDS_OTV_NOTO_C          "Номинальная толщина стенки отвода"
#define IDS_OTV_RATO            "Технологическое утонение, мм"
#define IDS_OTV_RATO_C          "Технологическое утонение стенки отвода"
#define IDS_KO_SEFF             "Эфф. площадь, кв.мм"
#define IDS_KO_SEFF_C           "Эффективная площадь осевого компенсатора"
#define IDS_KO_OS_HOD           "Осевой ход, мм"
#define IDS_KO_OS_HOD_C         "Осевой ход компенсатора"
#define IDS_KO_PODATL           "Податливость, мм/кг"
#define IDS_KO_PODATL_C         "Податливость осевого компенсатора"
#define IDS_KU_PODATL           "Податливость, рад/кг"
#define IDS_KU_PODATL_C         "Податливость углового компенсатора"
#define IDS_KU_LEN              "Длина, м"
#define IDS_KU_LEN_C            "Длина углового компенсатора"
#define IDS_TR_MAT              "Материал"
#define IDS_TR_MAT_C            "Материал тройника"
#define IDS_TR_VES              "Вес, кг"
#define IDS_TR_VES_C            "Вес тройника"
#define IDS_MAGISTRAL           "Магистраль:"
#define IDS_MAG_NOTO            "Номинальная толщина"
#define IDS_MAG_NOTO_C          "Номинальная толщина стенки магистрали"
#define IDS_MAG_RATO            "Технологич. утонение"
#define IDS_MAG_RATO_C          "Технологическое утонение"
#define IDS_MAG_LEN             "Длина магистрали"
#define IDS_MAG_LEN_C           "Длина магистрали"
#define IDS_OTV                 "Ответвление:"
#define IDS_OTV_DIAM            "Диаметр, мм"
#define IDS_OTV_DIAM_C          "Диаметр ответвления"
#define IDS_OSN                 "Основные"
#define IDS_FORMAT_PIPE         "Участок (%g-%g)"
#define IDS_FORMAT_NODE         "Узел (%g)"
#define IDS_FORMAT_MANY_PIPES   "Несколько участков/узлов:"
#define IDS_FORMAT_NODE2        "Узел (%d)"
#define IDS_FORMAT_PIPE2        "Участок (%d-%d)"
#define IDS_PODJOM              "Подъем"
#define IDS_OPUSK               "Опуск"
#define IDS_FORMAT_UCH_UZL      "Участков: %d  Узлов: %d"
#define IDS_FORMAT_PIPE_EXISTS  "Участок %d - %d уже существует"
#define IDS_ARMAT_TABLE         "Таблица арматуры"
#define IDS_STRING270           "Таблица арматуры"
#define IDS_AT_DIAM             "Диам."
#define IDS_PT_ROTV             "Rотв, м"
#define IDS_PT_VESARM           "Вес арм., кг"
#define IDS_PT_MATOTV           "Мат-л отв"
#define IDS_PT_SOTV             "Sотв, мм"
#define IDS_PT_C1OTV            "C1отв, мм"
#define IDS_PT_SEFF             "Sэфф, мм"
#define IDS_PT_KPOD             "Кпод, м"
#define IDS_OTVL_NOTO           "Номинальная толщина"
#define IDS_OTVL_NOTO_C         "Номинальная толщина стенки ответвления"
#define IDS_OTVL_RATO           "Технологич. утонение"
#define IDS_OTVL_RATO_C         "Технологическое утонение"
#define IDS_OTVL_VYS            "Высота, мм"
#define IDS_OTVL_VYS_C          "Высота ответвления"
#define IDS_NAKL                "Накладка:"
#define IDS_NAKL_NOTO           "Номинальная толщина"
#define IDS_NAKL_NOTO_C         "Номинальная толщина накладки"
#define IDS_NAKL_SHIR           "Ширина накладки"
#define IDS_NAKL_SHIR_C         "Ширина накладки"
#define IDS_VR_KOPR             "Коэф. прочн. сварного соединения"
#define IDS_VR_KOPR_C           "Коэфициент прочности сварного соединения"
#define IDS_VR_NAKL             "Накладки:"
#define IDS_VR_NAKL_NOTO        "Толщина, мм"
#define IDS_VR_NAKL_NOTO_C      "Толщина накладки"
#define IDS_VR_NAKL_SHIR        "Ширина, мм"
#define IDS_VR_NAKL_SHIR_C      "Ширина накладки"
#define IDS_MERT                "Мертвая"
#define IDS_SK                  "Скользящая"
#define IDS_NAPR                "Направляющая"
#define IDS_UPR                 "Упругая"
#define IDS_ZHESTK_PODV         "Жесткая подвеска"
#define IDS_OPOR                "Опора"
#define IDS_OPOR_C              "Тип опоры в узле"
#define IDS_MERT_O              "Мертвая опора"
#define IDS_SK_O                "Скользящая опора"
#define IDS_NAPR_O              "Направляющая опора"
#define IDS_SK_KOTR             "Коэфф. трения"
#define IDS_SK_KOTR_C           "Коэффициент трения в опоре"
#define IDS_UPR_O               "Упругая опора"
#define IDS_UPR_NTG             "Число тяг"
#define IDS_UPR_NTG_C           "Число тяг"
#define IDS_UPR_IZM_NAGR        "Изменение нагрузки, %"
#define IDS_UPR_IZM_NAGR_C      "Изменение нагрузки"
#define IDS_UPR_KZAP            "К-т запаса по нагрузке"
#define IDS_UPR_KZAP_C          "Коэффициент запаса по нагрузке"
#define IDS_UPR_PODD_US         "Поддерж. усилие, кг"
#define IDS_UPR_PODD_US_C       "Поддерживающее усилие"
#define IDS_UPR_PODATL          "Податливость, мм/кг"
#define IDS_ZHP_LEN_TYAGI       "Длина тяги, м"
#define IDS_ZHP_LEN_TYAGI_C     "Длина тяги"
#define IDS_RAST                "Растяжение"
#define IDS_SG                  "Сжатие"
#define IDS_DEF                 "Деформация"
#define IDS_DEF_C               "Тип деформации в узле"
#define IDS_DEF_RAST            "Растяжение, мм"
#define IDS_DEF_SG              "Сжатие, мм"
#define IDS_DEF_RSTSG_C         "Величина деформации, мм"
#define IDS_NAGR                "Нагрузки"
#define IDS_NAGR_VES_ADD        "Дополнительные весовые нагрузки"
#define IDS_UZ_SILVES           "Сила от веса, кг"
#define IDS_UZ_SILVES_C         "Сила от веса в узле"
#define IDS_UZ_MOMVESX          "Момент от веса вокруг X, кг·м"
#define IDS_UZ_MOMVESX_C        "Момент от веса вокруг X в узле"
#define IDS_UZ_MOMVESY          "Момент от веса вокруг Y, кг·м"
#define IDS_UZ_MOMVESY_C2       "Момент от веса вокруг Y в узле"
#define IDS_NAGR_NONVES_ADD     "Дополнительные невесовые нагрузки"
#define IDS_UZ_SILX             "Сила по оси X, кг"
#define IDS_UZ_SILX_C           "Невесовая сила по оси X"
#define IDS_UZ_SILY             "Сила по оси Y, кг"
#define IDS_UZ_SILY_C2          "Невесовая сила по оси Y"
#define IDS_UZ_SILZ             "Сила по оси Z, кг"
#define IDS_UZ_SILZ_C           "Невесовая сила по оси Z"
#define IDS_UZ_MOMX             "Момент вокруг оси X, кг·м"
#define IDS_UZ_MOMX_C           "Невесовой момент вокруг оси X"
#define IDS_UZ_MOMY             "Момент вокруг оси Y кг·м"
#define IDS_UZ_MOMY_C           "Невесовой момент вокруг оси Y"
#define IDS_UZ_MOMZ             "Момент вокруг оси Z кг·м"
#define IDS_UZ_MOMZ_C           "Невесовой момент вокруг оси Z"
#define IDS_UPR_PODATL_C        "Податливость"
#define IDS_PT_SHTR             "Шир.транш., м"
#define IDS_PT_PIPE_TYPE        "Тип трубы"
#define IDS_AT_S                "S, мм"
#define IDS_AT_C1               "C1, мм"
#define IDS_AT_ROTV             "Рад.отв.,мм"
#define IDS_AT_VESOTV           "Вес отв.,кг"
#define IDS_AT_LZADV            "Длина задв.,м"
#define IDS_AT_VESZADV          "Вес задв.,кг"
#define IDS_AT_NAGRMERT         "Нагр.мерт"
#define IDS_AT_NAGRSK           "Нагр.ск"
#define IDS_F_DIAM              "Диаметр трубы"
#define IDS_F_NAMA              "Материал трубы"
#define IDS_F_NTOS              "Ном.  толщина стенки трубы"
#define IDS_STRING284           "Технологическое утонение"
#define IDS_F_VETR              "Вес погонного метра трубы"
#define IDS_F_VEIZ              "Вес погонного метра изоляции"
#define IDS_F_VEPR              "Вес погонного метра продукта"
#define IDS_PDD_BY_WATER        "водой"
#define IDS_PDD_BY_AIR          "воздухом (газом)"
#define IDS_PDD_PERFORM         "проводить"
#define IDS_NORMA_OST           "ОСТ 108.764.01-80"
#define IDS_NORMA_MVN           "МВН 049-63"
#define IDS_NORMA_MN            "МН 3958-62"
#define IDS_NORMA_OST24         "ОСТ 24.125.109-01"
#define IDS_NORMA_LISEGA        "LISEGA"
#define IDS_WORK                "рабочее"
#define IDS_COLD                "холодное"
#define IDS_STRING330           "IDS"
#define IDS_PT_MAT              "Мат-л трубы"
#define IDS_PT_QTR              "qтр, кг/м"
#define IDS_PT_QI               "qи, кг/м"
#define IDS_PT_QP               "qп, кг/м"
#define IDS_PT_DIZ              "Dиз, мм"
#define IDS_PT_SIZ              "Sиз, мм"
#define IDS_PT_PODZ             "Подз."
#define IDS_PT_NADZ             "Надз."
#define IDS_PT_DEL_LINE_Q       "Удалить строку?"
#define IDS_DELETE_NODE_Q       "Удалить узел %d?"
#define IDS_MN_IZLOM1           "Точка излома в узле %d"
#define IDS_RENUM_NODES_Q       "Перенумеровать узлы на схеме?"
#define IDS_UNITE_NODES_Q       "После удаления участков нарушится связность трубопровода. Объединить узлы удаляемого фрагмента?"
#define IDS_F_RTOS              "Технологическое утонение"
#define IDS_TR_TABLE            "Таблица тройников"
#define IDS_C                   "C, мм"
#define IDS_DIAM_SHT            "Диам.шт"
#define IDS_S_SHT               "Sшт."
#define IDS_C_SHT               "Сшт."
#define IDS_VYS_SHT             "Выс.шт."
#define IDS_SHIR_NAKL           "Шир.накл"
#define IDS_TOLSCH_NAKL         "Толщ.накл"
#define IDS_VES_TR              "Вес тройника"
#define IDS_KORPUS              "KORPUS"
#endif